config/routes.rb
SampleApp::Application.routes.draw do
  resources :users do
      member do
          get :following, :followers
      end
    end
  get "static_pages/home"
  resources :relationships, only: [:create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  match '/signup', to: 'users#new',via: 'get'
  match '/signin', to: 'sessions#new',via: 'get'
  match '/signout', to: 'sessions#destroy',via: 'delete'
  match '/uploadfile',to:'users#upload_file',via: [:get, :post]
  root to: 'static_pages#home'
  match '/help',to: 'static_pages#help',via: 'get'
  match '/about',to: 'static_pages#about',via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :microposts, dependent: :destroy 
	has_many :relationships, foreign_key: "follower_id", dependent: :destroy
	has_many :followed_users, through: :relationships, source: :followed
	has_many :reverse_relationships, foreign_key: "followed_id",class_name: "Relationship",dependent: :destroy
	has_many :followers, through: :reverse_relationships, source: :follower
	before_save { self.email = email.downcase }
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence:true,format:{ with: VALID_EMAIL_REGEX },uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, length: { minimum: 6 }

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	def feed
			#Micropost.where("user_id = ?", id)
			Micropost.from_users_followed_by(self)
	end

	def following?(other_user)
		self.relationships.find_by(followed_id: other_user.id)
	end
	def follow!(other_user)
		self.relationships.create!(followed_id: other_user.id)
	end
	def unfollow!(other_user)
		self.relationships.find_by(followed_id: other_user.id).destroy
	end




	def User.picture_name_upload(file,email)
		dir_path = "#{Rails.root}/app/assets/images"
		if !File.exist?(dir_path)
			FileUtils.makedirs(dir_path)#文件不存在就创建文件
		end
		file_rename = email.downcase+"#{File.extname(file)}"
		file_path = "#{dir_path}/#{file_rename}"
		File.open(file_path,'wb+').write(file.read)
		store_path = "#{dir_path}/#{file_rename}"
		return store_path



	end

	def User.delete_picture_name(email)
		file_extname_array=[".jpg",".gif",".png",".jpeg"]
		file_extname_array.each do |extname|
			file_path = "#{Rails.root}/app/assets/images/#{email}"+extname
			if File.exist?(file_path)
				File.delete(file_path)
			end
		end
	end

	private
		def create_remember_token
			self.remember_token = User.encrypt(User.new_remember_token)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user,only: [:edit, :update]
  before_action :admin_user,only: :destroy
  before_action :signed_in_user,only: [:index, :edit, :update, :destroy, :following, :followers]

	def upload_file #上传文件
		email=params[:email]
		file=params[:user][:picture_name]
		User.delete_picture_name(email)#删除存在的文件
		userupdate=User.find_by_email(email)
		#userupdate.picture_name=User.picture_name_upload(file,email)#写入图片
		userupdate.save
		flash[:success] = "上传头像成功！"
		 redirect_to root_path
	end
  def index
  	@users = User.paginate(page: params[:page])
  end
  def new
  	@user = User.new
  end

  def edit
   	
   end

   def destroy
   	User.find(params[:id]).destroy
	flash[:success] = "User destroyed."
	redirect_to users_url
  end

  def show
  	@user = User.find(params[:id])
  	@microposts = @user.microposts.paginate(page: params[:page])
  end

  def create
	@user = User.new(user_params)
	# Not the final implementation!
	if @user.save
		# Handle a successful save.
		sign_in @user
		flash[:success] = "Welcome to the Sample App!"
		redirect_to @user
	else
		render 'edit'
	end
  end

  def update
	if @user.update_attributes(user_params)
		flash[:success] = "Profile updated"
		sign_in @user
		redirect_to @user
	else
		render 'edit'
	end
  end

	def following
		@title = "Following"
		@user = User.find(params[:id])
		@users = @user.followed_users.paginate(page: params[:page])
		render 'show_follow'
	end
	def followers
		@title = "Followers"
		@user = User.find(params[:id])
		@users = @user.followers.paginate(page: params[:page])
		render 'show_follow'
	end

  #private
  	def user_params
		params.require(:user).permit(:name, :email, :password,:password_confirmation)
	end

	def admin_user
		redirect_to(root_path) unless current_user.admin?
	end

	def correct_user
		@user = User.find(params[:id])
		redirect_to(root_path) unless current_user?(@user)
	end

	def correct_user
		@user = User.find(params[:id])
		redirect_to(root_path) unless current_user?(@user)
	end
end

app/helpers/users_helper.rb
module UsersHelper
	# Returns the Gravatar (http://gravatar.com/) for the given user.
	def gravatar_for(user, options = { size: 50 })
	gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
	#size = options[:size]
	gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
	image_tag(gravatar_url, alt: user.name, class: "gravatar",size: "60x60")
end
end

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
	<div id="follow_form">
		<% if current_user.following?(@user) %>
			<%= render 'shared/unfollow' %>
		<% else %>
			<%= render 'shared/follow' %>
		<% end %>
	</div>
<% end %>

app/views/users/_user.html.erb
<li>
<%= gravatar_for user, size: 52 %>
<%= link_to user.name, user %>
<% if current_user.admin? && !current_user?(user) %>
| <%= link_to "delete", user, method: :delete,data: { confirm: "You sure?" } %>
<% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>
<div class="row">
		<div class="span6 offset3">
			<%= form_for(@user) do |f| %>
				<%= render 'shared/error_messages', object: f.object %>
				<%= f.label :name %>
				<%= f.text_field :name %>
				<%= f.label :email %>
				<%= f.text_field :email %>
				<%= f.label :password %>
				<%= f.password_field :password %>
				<%= f.label :password_confirmation, "Confirm Password" %>
				<%= f.password_field :password_confirmation %>
				<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
			<% end %>
      <%= gravatar_for(@user) %>
      <div class="accordion" id="fileupaccordion">
        <div class="accordion-group">
          <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
              change
            </a>
          </div>
          <div id="collapseTwo" class="accordion-body collapse">
            <div class="accordion-inner">
              <form action="<%=uploadfile_path %>?email=<%=@user.email%>" multipart="true" method="post" accept-charset="utf-8">
                <input type="file" id="fileImage" name="user[picture_name]"  size="19" style="opacity: 1;" accept=".jpg,.gif,.png,.jpeg">
                <input type="submit" class="tn btn-small btn-primary" id="saveBtn">
              </form>
            </div>
          </div>
        </div>
      </div>
		</div>
</div>
<style>
  .accordion-group{
    width: 70%;
    float: right;
  }
  .accordion-group,.accordion-heading{
    border: none;
  }
  .accordion-inner{
    border: none;
  }
  .accordion-body input[type=file]{
    border: none;
    padding-left: 0;
  }
</style>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>
<ul class="users">
	<%#@users.each do |user| %>
		<%#= render user %>
	<%# end %>
	<%= render  @users %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
	<div class="span6 offset9">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' , object: f.object %>
			<%= f.label :name %>
			<%= f.text_field :name %>
			<%= f.label :email %>
			<%= f.text_field :email %>
			<%= f.label :password %>
			<%= f.password_field :password %>
			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation %>
			<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
	<aside class="span6">
		<section>
			<h1>
				<%= gravatar_for @user %>
				<%= @user.name %>
			</h1>
		</section>
		<section>
			<%= render 'shared/stats' %>
		</section>
	</aside>

	<div class="span6">
		<%= render 'follow_form' if signed_in? %>
		<% if @user.microposts.any? %>
		<h3>Microposts (<%= @user.microposts.count %>)</h3>
		<ol class="microposts">
			<%= render @microposts %>
		</ol>
		<%= will_paginate @microposts %>
		<% end %>
	</div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
	<aside class="span4">
		<section>
			<%= gravatar_for @user %>
			<h1><%= @user.name %></h1>
			<span><%= link_to "view my profile", @user %></span>
			<span><b>Microposts:</b> <%= @user.microposts.count %></span>
		</section>
		
		<section>
			<%= render 'shared/stats' %>
			<% if @users.any? %>
			<div class="user_avatars">
				<% @users.each do |user| %>
				<%= link_to gravatar_for(user, size: 30), user %>
				<% end %>
			</div>
			<% end %>
		</section>
	</aside>

	<div class="span8">
		<h3><%= @title %></h3>
		<% if @users.any? %>
			<ul class="users">
			<%= render @users %>
			</ul>
			<%= will_paginate %>
		<% end %>
	</div>
</div>